# Calculating Across Rows

How do we calculate row-wise in Pandas like we do in Excel?

<img src="https://sandeepmj.github.io/image-host/oil-v-gold.png">

We need a couple of new concepts to do this calculation:

1. Capture a number from a cell and hold in variable.
2. We `apply()`calculations across columns, row-wise, using using a `lambda expression`.


This is step one in your ability to accomplish tasks that are highly specialized to your beats.

In [3]:
## import library
import pandas as pd

In [4]:
## pull in data
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/oil-v-gold-pandas.csv")
df

         Date  PX_GOLD  PX_OIL
0     1/31/08    922.7   91.75
1     2/29/08    975.0  101.84
2     3/31/08    916.2  101.58
3     4/30/08    865.1  113.46
4     5/30/08    887.3  127.35
..        ...      ...     ...
116   9/29/17   1281.5   51.67
117  10/31/17   1270.5   54.38
118  11/30/17   1273.2   57.40
119  12/29/17   1309.3   60.42
120   1/31/18   1339.0   64.73

[121 rows x 3 columns]

What are the different values for row **TWO** in this formula for `PX_GOLD`:

$$\text{Pct Chg at time } t = \frac{\text{Value at time } t - \text{Value at start time}}{\text{Value at start time}} \times 100$$

Use `.iat` to store a value from a specific cell into a variable:

```dataframe["column_name"].iat[row_index_number]```

In [6]:
## hold gold
df["PX_GOLD"].iat[0]

np.float64(922.7)

Also works:

`dataframe.iat[col_index_number, row_index_number]`

In [9]:
## hold gold col index, row index
gold_start = df.iat[0,1]
gold_start

np.float64(922.7)

Place the value for the starting oil price in a variable called `oil_baseline`

In [10]:
## oil_baseline
oil_start = df.iat[0,2]
oil_start

np.float64(91.75)

# `lambda expressions`

We're going to just write one first and then break it down:

In [12]:
## create a new column that holds the zero index for gold
df["gold_zero_index"] = df["PX_GOLD"].apply(lambda x: (x-gold_start)/gold_start * 100)
df

         Date  PX_GOLD  PX_OIL  gold_zero_index
0     1/31/08    922.7   91.75         0.000000
1     2/29/08    975.0  101.84         5.668148
2     3/31/08    916.2  101.58        -0.704454
3     4/30/08    865.1  113.46        -6.242549
4     5/30/08    887.3  127.35        -3.836567
..        ...      ...     ...              ...
116   9/29/17   1281.5   51.67        38.885878
117  10/31/17   1270.5   54.38        37.693725
118  11/30/17   1273.2   57.40        37.986344
119  12/29/17   1309.3   60.42        41.898775
120   1/31/18   1339.0   64.73        45.117590

[121 rows x 4 columns]

## What  `x` stand for:

- In Pandas, we `apply()` lambda expressions to columns.
-  `.apply()`  works element-wise on each value in the `PX_GOLD` column, one at a time.
- `x` is a single value representing a cell in the column `PX_GOLD`
- The ```lambda x:``` processes each row of a dataframe, one row at a time.
-  The `lambda expression` takes each individual number `x` from `PX_GOLD` and runs the indexing formula on it.

Think of it as: "call each value in `PX_GOLD` as `x`, and do this math to using `x` in the formula."

## create a new column that holds the zero index for oil

In [19]:
## zero index oil
df["oil_zero_index"] = df["PX_OIL"].apply(lambda x: (x-oil_start)/oil_start * 100)

In [20]:
## call df
df

         Date  PX_GOLD  PX_OIL  gold_zero_index  oil_zero_index
0     1/31/08    922.7   91.75         0.000000        0.000000
1     2/29/08    975.0  101.84         5.668148       10.997275
2     3/31/08    916.2  101.58        -0.704454       10.713896
3     4/30/08    865.1  113.46        -6.242549       23.662125
4     5/30/08    887.3  127.35        -3.836567       38.801090
..        ...      ...     ...              ...             ...
116   9/29/17   1281.5   51.67        38.885878      -43.683924
117  10/31/17   1270.5   54.38        37.693725      -40.730245
118  11/30/17   1273.2   57.40        37.986344      -37.438692
119  12/29/17   1309.3   60.42        41.898775      -34.147139
120   1/31/18   1339.0   64.73        45.117590      -29.449591

[121 rows x 5 columns]

### 100-indexing

Create cells below to add columns for both oil and gold for 100-indexing.

Reminder, the formula for 100-indexing:

$$\text{Index} = \left(\frac{\text{value at time } t}{\text{value at start}}\right) \times 100$$

In [35]:
## gold 100
df["gold_100_index"] = df["PX_GOLD"].apply(lambda x: round((x/gold_start) * 100, 1 ))
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index,oil_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.0
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,111.0
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.7
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.7
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.8
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.3
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.3
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.6
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.9
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.6

In [36]:
## oil 100
df["oil_100_index"] = df["PX_OIL"].apply(lambda x: round((x/oil_start) * 100, 1 ))
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index,oil_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.0
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,111.0
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.7
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.7
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.8
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.3
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.3
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.6
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.9
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.6

# Homework

<a href="https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv">This dataset</a> shows the price of a standard cable subscription and the U.S. median income annually between 1995-2023.

Has median income kept pace with the price of a cable subscription?

Round all numbers to 1 decimal place

In [ ]:
## read file

In [ ]:
## get info

### Index cable billl

In [ ]:
## cable_baseline

In [ ]:
## cable bill index

### Index median income

In [ ]:
## income_baseline

In [ ]:
## median income index

In [ ]:
## analysis